# Generated by Django 5.2.6 on 2026-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="valid_form",
            new_name="valid_from",
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="coupons_cou_code_3bf721_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["active"], name="coupons_cou_active_9d348c_idx"),
        ),
    ]
