# Generated by Django 5.2.6 on 2026-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_translations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created"]},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["id"], name="shop_catego_id_d67477_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["available"], name="shop_produc_availab_47d513_idx"
            ),
        ),
    ]
