# Generated by Django 5.2.6 on 2026-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_rename_valid_form_coupon_valid_from_and_more"),
        ("orders", "0003_order_coupon_order_discount"),
        ("shop", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=250, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="postal code"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["paid"], name="orders_orde_paid_34f5f6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["email"], name="orders_orde_email_88c705_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="orders_orde_order_i_52f79a_idx"
            ),
        ),
    ]
